// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM3A_HhFvoxZoBAffE3RgrzwxmRcBaJZs',
    appId: '1:941126995741:web:4e168580a931540ec19bf4',
    messagingSenderId: '941126995741',
    projectId: 'fir-flutter-3b699',
    authDomain: 'fir-flutter-3b699.firebaseapp.com',
    storageBucket: 'fir-flutter-3b699.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0SS-f3OQi2ETFYRXrF9DRjqItXWEdi20',
    appId: '1:941126995741:android:8eb88d58c9542bf7c19bf4',
    messagingSenderId: '941126995741',
    projectId: 'fir-flutter-3b699',
    storageBucket: 'fir-flutter-3b699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhI265JJsBJryCAfDrStRALkbqQSIi8zE',
    appId: '1:941126995741:ios:d04dbc370e7ddc0ec19bf4',
    messagingSenderId: '941126995741',
    projectId: 'fir-flutter-3b699',
    storageBucket: 'fir-flutter-3b699.appspot.com',
    iosClientId: '941126995741-e2o4siu4cu9dpn6l4c6otb3pc5f6s2s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhI265JJsBJryCAfDrStRALkbqQSIi8zE',
    appId: '1:941126995741:ios:d04dbc370e7ddc0ec19bf4',
    messagingSenderId: '941126995741',
    projectId: 'fir-flutter-3b699',
    storageBucket: 'fir-flutter-3b699.appspot.com',
    iosClientId: '941126995741-e2o4siu4cu9dpn6l4c6otb3pc5f6s2s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
